# Generated by Django 4.2.30 on 2026-07-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
