# Generated by Django 4.2.30 on 2026-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_portfolioitem_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali'), ('ar', 'Arabic')], db_index=True, default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali'), ('ar', 'Arabic')], db_index=True, default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddConstraint(
            model_name='portfolioitem',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='cms_portfolio_language_slug'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='cms_post_language_slug'),
        ),
    ]
