# Generated by Django 4.2.30 on 2026-07-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('service', models.CharField(max_length=200, verbose_name='service needed')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='preferred date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'appointment request',
                'verbose_name_plural': 'appointment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='portal user'),
        ),
    ]
