# Generated by Django 4.2.30 on 2026-07-06 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status changed')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(choices=[('matter', 'Matter'), ('document', 'Document'), ('transaction', 'Transaction'), ('client', 'Client')], max_length=20, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='entity id')),
                ('entity_label', models.CharField(max_length=255, verbose_name='entity')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='logged at')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.matter', verbose_name='matter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
            },
        ),
    ]
